version: '3'
services:
  postgres:
    container_name: notes_postgres
    image: postgres
    restart: unless-stopped
    environment: 
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/postgresdb:/data/postgresdb
    ports:
      - '5432:5432'